from typing import ClassVar

from . import psl as psl

class PslType:
    ALL: ClassVar[PslType]
    ICANN: ClassVar[PslType]
    PRIVATE: ClassVar[PslType]

class DomainInfo:
    @property
    def domain(self) -> str: ...
    @property
    def suffix(self) -> str: ...
    @property
    def psl(self) -> PslType | None: ...

class ParsedURL:
    @property
    def href(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def authority(self) -> str: ...
    @property
    def netloc(self) -> str: ...
    @property
    def hostname(self) -> str | None: ...
    @property
    def port(self) -> int | None: ...
    @property
    def path(self) -> str: ...
    @property
    def query(self) -> str | None: ...
    @property
    def fragment(self) -> str | None: ...
    @property
    def username(self) -> str: ...
    @property
    def password(self) -> str | None: ...
    @property
    def domain(self) -> str | None: ...
    @property
    def host_ip_version(self) -> int | None: ...
    def path_parts(self) -> list[str]: ...
    def query_params(self) -> dict[str, str]: ...
    def domain_info(self) -> DomainInfo | None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class URL:
    @property
    def href(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @scheme.setter
    def scheme(self, value: str) -> None: ...
    @property
    def authority(self) -> str: ...
    @property
    def netloc(self) -> str: ...
    @property
    def hostname(self) -> str | None: ...
    @hostname.setter
    def hostname(self, value: str | None) -> None: ...
    @property
    def port(self) -> int | None: ...
    @port.setter
    def port(self, value: int | None) -> None: ...
    @property
    def path(self) -> str: ...
    @path.setter
    def path(self, value: str | None) -> None: ...
    @property
    def query(self) -> str | None: ...
    @query.setter
    def query(self, value: str | None) -> None: ...
    @property
    def fragment(self) -> str | None: ...
    @fragment.setter
    def fragment(self, value: str | None) -> None: ...
    @property
    def username(self) -> str: ...
    @username.setter
    def username(self, value: str | None) -> None: ...
    @property
    def password(self) -> str | None: ...
    @password.setter
    def password(self, value: str | None) -> None: ...
    @property
    def domain(self) -> str | None: ...
    @property
    def host_ip_version(self) -> int | None: ...
    def path_parts(self) -> list[str]: ...
    def query_params(self) -> dict[str, str]: ...
    def domain_info(self) -> DomainInfo | None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    __hash__: None  # type: ignore[assignment]
    @staticmethod
    def parse(url_str: str, psl: PslType | None = ...) -> URL: ...

def parse(url_str: str, psl: PslType | None = ...) -> ParsedURL: ...
